---
title: "Figure 3"
output:
  html_document:
    code_download: true
    code_folding: hide
    toc: true
    toc_float:
      collapsed: true
---

# Disclaimer

This script has one purpose only, which is to assemble a figure for the main text. This is all cobbled together from code from previous workflows, and is not meant to be elegant or expository.

# Setup

```{r libraries}
library(tidyverse)
library(here)
library(patchwork)

library(glmmTMB)
library(broom.mixed)

source(here("code", "utils", "modeling_utils.R"))
source(here("code", "utils", "representation_utils.R"))

source(here("code", "utils", "ggplot_themes.R"))
source(here("code", "utils", "unicode_greek.R"))

knitting <- knitr::is_html_output()

create_path <- function(this_path) {
  if (!dir.exists(this_path)) {
    dir.create(this_path, recursive = TRUE)
  }
}

predict_glmmTMB <- function(make_predictions_for, model_object) {
  make_predictions_for %>%
    bind_cols(
      predict(
        object = model_object,
        newdata = .,
        re.form = NA, allow.new.levels = TRUE, se.fit = TRUE, type = "response"
      )
    )
}

if (knitting) {
  here("figures") %>%
    create_path()
}
```


# After overnight rest

```{r load-behav-data}
nav_study2 <- here("data", "clean_data", "study2_message_passing.csv") %>%
  read_csv(show_col_types = FALSE) %>%
  filter(
    two_correct_options == FALSE,
    shortest_path_given_opts == shortest_path_given_start_end
  ) %>%
  mutate(
    study = "Study 2",
    measurement_id = case_when(
      network == "learned" ~ str_c("D", measurement_id),
      network == "reevaluated" ~ "D2b"
    ),
    shortest_path = factor(shortest_path_given_opts)
  ) %>%
  select(
    study, sub_id, measurement_id, shortest_path,
    startpoint_id, endpoint_id,
    opt1_id, opt2_id,
    correct_choice, sub_choice,
    correct, rt
  ) %>%
  filter(measurement_id %in% c("D1", "D2"))

nav_study3 <- here("data", "clean_data", "study3_message_passing.csv") %>%
  read_csv(show_col_types = FALSE) %>%
  filter(
    two_correct_options == FALSE,
    shortest_path_given_opts == shortest_path_given_start_end
  ) %>%
  mutate(
    study = "Study 3",
    measurement_id = case_when(
      network == "reevaluated" ~ "D2b",
      measurement_id == 1 ~ "D1",
      measurement_id == 2 ~ "D1b",
      measurement_id == 3 ~ "D2"
    ),
    shortest_path = factor(shortest_path_given_opts)
  ) %>%
  select(
    study, sub_id, measurement_id, shortest_path,
    startpoint_id, endpoint_id,
    opt1_id, opt2_id,
    correct_choice, sub_choice,
    correct, rt
  ) %>%
  filter(measurement_id %in% c("D1", "D1b", "D2"))
```

```{r plot-overnight-rest}
nav_day1_to_day2 <- bind_rows(nav_study2, nav_study3) %>%
  filter(measurement_id %in% c("D1", "D2")) %>%
  # Give every subject a distinct identifier
  mutate(sub_id = str_c(study, " s", sub_id))

stats_nav_day2_dist2 <- nav_day1_to_day2 %>%
  mutate(shortest_path = fct_relevel(shortest_path, "2")) %>%
  glmmTMB(
    correct ~ shortest_path * measurement_id +
      (1 + shortest_path + measurement_id | sub_id) + (1 | study),
    family = binomial,
    data = .
  )

predict_nav_day1_to_day2 <- expand_grid(
  measurement_id = c("D1", "D2"),
  shortest_path = factor(2:4),
  sub_id = NA, study = NA
) %>%
  predict_glmmTMB(stats_nav_day2_dist2)

plot_nav_day1_to_day2 <- nav_day1_to_day2 %>%
  group_by(sub_id, measurement_id, shortest_path) %>%
  summarise(accuracy = mean(correct), .groups = "drop") %>%
  ggplot(aes(x=shortest_path, y=accuracy, color=measurement_id)) +
  theme_custom() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  geom_dotplot(
    aes(fill = measurement_id),
    binwidth = 0.01,
    binaxis = "y", stackdir = "center",
    position = position_dodge(width = 0.75),
    dotsize = 2, alpha = 0.5, color = NA,
    show.legend = FALSE
  ) +
  geom_pointrange(
    aes(
      x = shortest_path, y = fit,
      ymin = fit - se.fit, ymax = fit + se.fit,
      color = measurement_id
    ),
    data = predict_nav_day1_to_day2, inherit.aes = FALSE, show.legend = FALSE,
    position = position_dodge(width = 0.15), linewidth = 1
  ) +
  geom_line(
    aes(
      x = shortest_path, y = fit,
      group = measurement_id, color = measurement_id
    ),
    data = predict_nav_day1_to_day2, inherit.aes = FALSE,
    position = position_dodge(width = 0.15), linewidth = 1
  ) +
  scale_x_discrete(name = "Shortest path distance") +
  scale_y_continuous(
    name = "Accuracy", labels = scales::percent, breaks = seq(0, 1, 0.25)
  ) +
  scale_color_manual(
    name = "Measurement",
    values = c("D1"="#fa9fb5", "D2"="#7a0177"),
    labels = c("D1"="Before rest", "D2"="After overnight rest")
  ) +
  scale_fill_manual(values = c("D1"="#fa9fb5", "D2"="#7a0177")) +
  coord_cartesian(ylim = c(0.25, 1.1)) +
  theme(legend.position = "bottom") +
  ggtitle("Human behavior after overnight rest")

plot_nav_day1_to_day2
```


# After awake rest

```{r plot-awake-rest}
stats_nav_awake_dist2 <- nav_study3 %>%
  filter(measurement_id %in% c("D1", "D1b")) %>%
  mutate(shortest_path = fct_relevel(shortest_path, "2")) %>%
  glmmTMB(
    correct ~ shortest_path * measurement_id +
      (1 + shortest_path + measurement_id | sub_id),
    family = binomial,
    data = .
  )

predict_nav_awake <- expand_grid(
  measurement_id = c("D1", "D1b"),
  shortest_path = factor(2:4),
  sub_id = NA, study = NA
) %>%
  predict_glmmTMB(stats_nav_awake_dist2)

plot_nav_awake <- nav_study3 %>%
  filter(measurement_id %in% c("D1", "D1b")) %>%
  group_by(sub_id, measurement_id, shortest_path) %>%
  summarise(accuracy = mean(correct), .groups = "drop") %>%
  ggplot(aes(x=shortest_path, y=accuracy, color=measurement_id)) +
  theme_custom() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  geom_dotplot(
    aes(fill = measurement_id),
    binwidth = 0.01,
    binaxis = "y", stackdir = "center",
    position = position_dodge(width = 0.75),
    dotsize = 2, alpha = 0.5, color = NA,
    show.legend = FALSE
  ) +
  geom_pointrange(
    aes(
      x = shortest_path, y = fit,
      ymin = fit - se.fit, ymax = fit + se.fit,
      color = measurement_id
    ),
    data = predict_nav_awake, inherit.aes = FALSE, show.legend = FALSE,
    position = position_dodge(width = 0.15), linewidth = 1
  ) +
  geom_line(
    aes(
      x = shortest_path, y = fit,
      group = measurement_id, color = measurement_id
    ),
    data = predict_nav_awake, inherit.aes = FALSE,
    position = position_dodge(width = 0.15), linewidth = 1
  ) +
  scale_x_discrete(name = "Shortest path distance") +
  scale_y_continuous(
    name = "Accuracy", labels = scales::percent, breaks = seq(0, 1, 0.25)
  ) +
  scale_color_manual(
    name = "Measurement",
    values = c("D1"="#fa9fb5", "D1b"="#2c7fb8"),
    labels = c("D1"="Before rest", "D1b"="After awake rest")
  ) +
  scale_fill_manual(values = c("D1"="#fa9fb5", "D1b"="#2c7fb8")) +
  coord_cartesian(ylim = c(0.25, 1.1)) +
  theme(legend.position = "bottom") +
  ggtitle("Human behavior after awake rest")

plot_nav_awake
```


# Replay simulations

```{r data-for-sr-replay}
sr_obs <- here("data", "sr_obs", "sim_obs_for_sr.csv") %>%
  read_csv(show_col_types = FALSE)

nav_trials <- nav_study2 %>%
  filter(sub_id == 1, measurement_id == "D1") %>%
  select(
    shortest_path, startpoint_id, endpoint_id, opt1_id, opt2_id, correct_choice
  ) %>%
  arrange(shortest_path, startpoint_id, endpoint_id, opt1_id, opt2_id)

sr_replay_rep <- expand_grid(
  n_iter = c(0, 5, 10, 50, 1000) + 6,
  sr_gamma = seq(0.1, 0.9, 0.1)
) %>%
  rowwise() %>%
  mutate(
    sr = map(
      .x = n_iter,
      .f = ~build_successor_td_0(
        # 13 = number of nodes in network
        successor_matrix = diag(nrow = 13, ncol = 13),
        observation_matrix = sr_obs %>%
          filter(iter <= .x) %>%
          select(from, to) %>%
          as.matrix(),
        sr_alpha = 0.1,
        sr_gamma = sr_gamma,
        bidirectional = TRUE
      ) %>%
        mutate(sr_value = sr_value * (1-sr_gamma)) %>%
        select(-sr_gamma)
    )
  ) %>%
  ungroup() %>%
  unnest(sr)

sr_replay_nav <- expand_grid(
  n_iter = c(0, 5, 10, 50, 1000) + 6,
  sr_gamma = seq(0.1, 0.9, 0.1),
  nav_trials
) %>%
  left_join(
    sr_replay_rep %>%
      select(
        n_iter, sr_gamma,
        endpoint_id = to, opt1_id = from, opt1_sr = sr_value
      ),
    by = join_by(n_iter, sr_gamma, endpoint_id, opt1_id)
  ) %>%
  left_join(
    sr_replay_rep %>%
      select(
        n_iter, sr_gamma,
        endpoint_id = to, opt2_id = from, opt2_sr = sr_value
      ),
    by = join_by(n_iter, sr_gamma, endpoint_id, opt2_id)
  ) %>%
  rowwise() %>%
  mutate(
    predicted = softmax(
      option_values = c(opt1_sr, opt2_sr),
      option_chosen = if_else(opt1_id == correct_choice, 1, 2),
      temperature = 100,
      use_inverse_temperature = TRUE
    )
  ) %>%
  ungroup()
```

```{r plot-replay-sims}
plot_replay <- sr_replay_nav %>%
  group_by(n_iter, sr_gamma, shortest_path) %>%
  summarise(accuracy = mean(predicted), .groups = "drop") %>%
  mutate(
    n_iter = n_iter - 6,
    n_iter = if_else(
      n_iter == 0,
      "No replay",
      str_c(
        str_pad(n_iter, width = 4, side = "left"),
        " replay iter."
      )
    ),
    n_iter = fct_relevel(
      n_iter,
      "No replay"
    )
  ) %>%
  ggplot(aes(x=shortest_path, y=accuracy, color=sr_gamma)) +
  theme_custom() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  facet_wrap(~n_iter, nrow = 1) +
  geom_line(aes(group = sr_gamma), linewidth = 0.8) +
  scale_color_viridis_c(
    name = str_c(unicode_greek["gamma"], " ="),
    option = "turbo", end = 0.9, direction = -1
  ) +
  scale_x_discrete(name = "Shortest path distance") +
  scale_y_continuous(
    name = "Accuracy", labels = scales::percent, breaks = seq(0, 1, .25)
  ) +
  coord_cartesian(ylim = c(0.5, 1)) +
  theme(legend.position = "bottom") +
  ggtitle("Simulated SR-replay")

plot_replay
```


# Changes in gamma

```{r plot-gamma-increase}
params <- here("data", "param_fits", "clean_params", "clean_param_fits.csv") %>%
  read_csv(show_col_types = FALSE)

changes_in_gamma <- params %>%
  filter(
    study %in% c("Study 2", "Study 3"),
    measurement_id %in% c("D1", "D2"),
    model == "sr_analytic",
    param_name == "sr_gamma"
  ) %>%
  select(study, sub_id, measurement_id, sr_gamma = param_value) %>%
  mutate(lookahead = 1/(1-sr_gamma)) %>%
  arrange(study, sub_id, measurement_id) %>%
  group_by(study, sub_id) %>%
  mutate(
    delta_gamma = sr_gamma - first(sr_gamma),
    delta_lookahead = lookahead - first(lookahead)
  ) %>%
  ungroup()

plot_gamma_change <- changes_in_gamma %>%
  select(study, sub_id, measurement_id, sr_gamma) %>%
  ggplot(aes(x=measurement_id, y=sr_gamma)) +
  theme_custom() +
  geom_dotplot(
    aes(fill = measurement_id),
    binwidth = 0.01,
    binaxis = "y", stackdir = "center",
    dotsize = 3, alpha = 0.5, color = NA,
    show.legend = FALSE
  ) +
  geom_line(aes(group = interaction(study, sub_id)), alpha = 0.1) +
  stat_summary(
    aes(group = 1), geom = "line", fun = median, linewidth = 1
  ) +
  scale_fill_manual(values = c("D1"="#fa9fb5", "D2"="#7a0177")) +
  scale_x_discrete(
    name = "Measurement",
    labels = c("D1"="Before rest", "D2"="After overnight rest")
  ) +
  scale_y_continuous(
    name = str_c("Estimated ", unicode_greek["gamma"]),
    breaks = seq(0, 1, 0.25)
  ) +
  coord_cartesian(ylim = c(0, 1.1)) +
  theme(legend.position = "bottom") +
  ggtitle(
    str_c(
      unicode_greek["Delta"], unicode_greek["gamma"], " after overnight rest"
    )
  )

plot_gamma_change
```


# Relating changes in behavior and gamma

```{r plot-changes}
changes_in_behavior <- bind_rows(nav_study2, nav_study3) %>%
  filter(measurement_id %in% c("D1", "D2")) %>%
  group_by(study, sub_id, measurement_id, shortest_path) %>%
  summarise(accuracy = mean(correct), .groups = "drop") %>%
  arrange(study, sub_id, shortest_path, measurement_id) %>%
  group_by(study, sub_id, shortest_path) %>%
  mutate(delta_accuracy = accuracy - first(accuracy)) %>%
  ungroup()

plot_gamma_accuracy_change <- changes_in_behavior %>%
  filter(measurement_id == "D2") %>%
  left_join(
    changes_in_gamma %>%
      filter(measurement_id == "D2"),
    by = join_by(study, sub_id, measurement_id)
  ) %>%
  mutate(shortest_path = str_c("Dist-", shortest_path)) %>%
  ggplot(aes(x=delta_gamma, y=delta_accuracy, color=shortest_path)) +
  theme_custom() +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_point(alpha = 0.25, show.legend = FALSE) +
  geom_smooth(method = "lm", se = FALSE, linewidth = 1.5) +
  scale_x_continuous(name = str_c("Change in ", unicode_greek["gamma"])) +
  scale_y_continuous(name = "Change in accuracy") +
  scale_color_manual(
    name = NULL,
    values = c("#88CCEE", "#CC6677", "#DDCC77")
  ) +
  coord_cartesian(xlim = c(-1, 1.1)) +
  theme(legend.position = c(0.15, 0.8)) +
  ggtitle(
    str_c(
      unicode_greek["Delta"], "Navigation ~ ",
      unicode_greek["Delta"], unicode_greek["gamma"]
    )
  )

plot_gamma_accuracy_change
```


# Save figure

```{r save-figure}
plot_figure_3 <- (plot_nav_day1_to_day2 | plot_nav_awake) /
  plot_replay /
  (plot_gamma_change | plot_gamma_accuracy_change) +
  plot_annotation(
    title = "Social navigation after rest",
    tag_levels = "A", tag_suffix = ".",
    theme = theme(plot.title = element_text(hjust = 0.5))
  )

plot_figure_3

if (knitting) {
  suppressWarnings(
    ggsave(
      filename = here("figures", "fig3.pdf"),
      plot = plot_figure_3,
      scale = 2,
      width = 100, height = 120, units = "mm", dpi = 300
    )
  )
  
  ggsave(
    filename = here("figures", "fig3_cairo.pdf"),
    plot = plot_figure_3,
    scale = 2,
    width = 100, height = 120, units = "mm", dpi = 300,
    device = cairo_pdf
  )
}
```

