---
title: "Figure 1"
output:
  html_document:
    code_download: true
    code_folding: hide
    toc: true
    toc_float:
      collapsed: true
---

# Disclaimer

This script has one purpose only, which is to assemble a figure for the main text. This is all cobbled together from code from previous workflows, and is not meant to be elegant or expository.

# Setup

```{r libraries}
library(tidyverse)
library(here)
library(patchwork)

library(tidygraph)
library(ggraph)

source(here("code", "utils", "ggplot_themes.R"))
source(here("code", "utils", "unicode_greek.R"))

knitting <- knitr::is_html_output()

create_path <- function(this_path) {
  if (!dir.exists(this_path)) {
    dir.create(this_path, recursive = TRUE)
  }
}

if (knitting) {
  here("figures") %>%
    create_path()
}
```


# Network visualizations

```{r load-network-data}
adjlist <- here("data", "clean_data", "adjlist_learned.csv") %>%
  read_csv(show_col_types = FALSE)

g <- adjlist %>%
  filter(from < to, edge == 1) %>%
  select(-edge) %>%
  tbl_graph(edges = ., directed = FALSE)

adjlist_reevaluated <- here("data", "clean_data", "adjlist_reevaluated.csv") %>%
  read_csv(show_col_types = FALSE)

g_reevaluated <- adjlist_reevaluated %>%
  filter(from < to, edge == 1) %>%
  select(-edge) %>%
  tbl_graph(edges = ., directed = FALSE)
```

```{r plot-networks}
plot_network_learned <- g %>%
  mutate(name = row_number()) %>%
  ggraph("stress") +
  theme_network() +
  geom_edge_link() +
  geom_node_label(aes(label = name))

plot_network_reevaluated <- g_reevaluated %>%
  mutate(name = row_number()) %>%
  ggraph("stress") +
  theme_network() +
  geom_edge_link() +
  geom_node_label(aes(label = name))

plot_network_learned
plot_network_reevaluated

if (knitting) {
  ggsave(
    here("figures", str_c("fig1_network_learned", ".pdf")),
    plot = plot_network_learned,
    width = 4, height = 2,
    units = "in", dpi = 300
  )
  
  ggsave(
    here("figures", str_c("fig1_network_reevaluated", ".pdf")),
    plot = plot_network_reevaluated,
    width = 4, height = 2,
    units = "in", dpi = 300
  )
}
```

